apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
            namespace: argocd1
          - cluster: engineering-dev2
            url: https://kubernetes.default.svc
            namespace: argocd2
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
