apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://35.233.139.33
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: 14a3dc9e
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      syncPolicy:
        preserveResourcesOnDeletion: true 
        automated:     
          selfHeal: true 
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: mirko-test2
