apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: cluster1
            url: https://kubernetes.default.svc
          - cluster: cluster2
            url: https://kubernetes.default.svc
          - cluster: cluster3
            url: https://kubernetes.default.svc
          - cluster: cluster4
            url: https://kubernetes.default.svc
          - cluster: cluster5
            url: https://kubernetes.default.svc
          - cluster: cluster6
            url: https://kubernetes.default.svc
          - cluster: cluster7
            url: https://kubernetes.default.svc
          - cluster: cluster8
            url: https://kubernetes.default.svc
          - cluster: cluster9
            url: https://kubernetes.default.svc
          - cluster: cluster10
            url: https://kubernetes.default.svc
          - cluster: cluster11
            url: https://kubernetes.default.svc
          - cluster: cluster12
            url: https://kubernetes.default.svc
          - cluster: cluster13
            url: https://kubernetes.default.svc
          - cluster: cluster14
            url: https://kubernetes.default.svc
          - cluster: cluster15
            url: https://kubernetes.default.svc
          - cluster: cluster16
            url: https://kubernetes.default.svc
          - cluster: cluster17
            url: https://kubernetes.default.svc
          - cluster: cluster18
            url: https://kubernetes.default.svc
          - cluster: cluster19
            url: https://kubernetes.default.svc
          - cluster: cluster20
            url: https://kubernetes.default.svc
          - cluster: cluster21
            url: https://kubernetes.default.svc
          - cluster: cluster22
            url: https://kubernetes.default.svc
          - cluster: cluster23
            url: https://kubernetes.default.svc
          - cluster: cluster24
            url: https://kubernetes.default.svc
          - cluster: cluster25
            url: https://kubernetes.default.svc
          - cluster: cluster26
            url: https://kubernetes.default.svc
          - cluster: cluster27
            url: https://kubernetes.default.svc
          - cluster: cluster28
            url: https://kubernetes.default.svc
          - cluster: cluster29
            url: https://kubernetes.default.svc
          - cluster: cluster30
            url: https://kubernetes.default.svc
          - cluster: cluster31
            url: https://kubernetes.default.svc
          - cluster: cluster32
            url: https://kubernetes.default.svc
          - cluster: cluster33
            url: https://kubernetes.default.svc
          - cluster: cluster34
            url: https://kubernetes.default.svc
          - cluster: cluster35
            url: https://kubernetes.default.svc
          - cluster: cluster36
            url: https://kubernetes.default.svc
          - cluster: cluster37
            url: https://kubernetes.default.svc
          - cluster: cluster38
            url: https://kubernetes.default.svc
          - cluster: cluster39
            url: https://kubernetes.default.svc
          - cluster: cluster40
            url: https://kubernetes.default.svc
          - cluster: muster1
            url: https://kubernetes.default.svc
          - cluster: muster2
            url: https://kubernetes.default.svc
          - cluster: muster3
            url: https://kubernetes.default.svc
          - cluster: muster4
            url: https://kubernetes.default.svc
          - cluster: muster5
            url: https://kubernetes.default.svc
          - cluster: muster6
            url: https://kubernetes.default.svc
          - cluster: muster7
            url: https://kubernetes.default.svc
          - cluster: muster8
            url: https://kubernetes.default.svc
          - cluster: muster9
            url: https://kubernetes.default.svc
          - cluster: muster10
            url: https://kubernetes.default.svc
          - cluster: muster11
            url: https://kubernetes.default.svc
          - cluster: muster12
            url: https://kubernetes.default.svc
          - cluster: muster13
            url: https://kubernetes.default.svc
          - cluster: muster14
            url: https://kubernetes.default.svc
          - cluster: muster15
            url: https://kubernetes.default.svc
          - cluster: muster16
            url: https://kubernetes.default.svc
          - cluster: muster17
            url: https://kubernetes.default.svc
          - cluster: muster18
            url: https://kubernetes.default.svc
          - cluster: muster19
            url: https://kubernetes.default.svc
          - cluster: muster20
            url: https://kubernetes.default.svc
          - cluster: muster21
            url: https://kubernetes.default.svc
          - cluster: muster22
            url: https://kubernetes.default.svc
          - cluster: muster23
            url: https://kubernetes.default.svc
          - cluster: muster24
            url: https://kubernetes.default.svc
          - cluster: muster25
            url: https://kubernetes.default.svc
          - cluster: muster26
            url: https://kubernetes.default.svc
          - cluster: muster27
            url: https://kubernetes.default.svc
          - cluster: muster28
            url: https://kubernetes.default.svc
          - cluster: muster29
            url: https://kubernetes.default.svc
          - cluster: muster30
            url: https://kubernetes.default.svc
          - cluster: muster31
            url: https://kubernetes.default.svc
          - cluster: muster32
            url: https://kubernetes.default.svc
          - cluster: muster33
            url: https://kubernetes.default.svc
          - cluster: muster34
            url: https://kubernetes.default.svc
          - cluster: muster35
            url: https://kubernetes.default.svc
          - cluster: muster36
            url: https://kubernetes.default.svc
          - cluster: muster37
            url: https://kubernetes.default.svc
          - cluster: muster38
            url: https://kubernetes.default.svc
          - cluster: muster39
            url: https://kubernetes.default.svc
          - cluster: muster40
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: HEAD
        path: fake-guestbook-list/fake-guestbook
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-guestbook'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
        - Prune=true
        - PruneLast=true
