apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glob-char-class
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-valueFiles-glob
    helm:
      valueFiles:
      - values/char-class/[a-b].yaml # a.yaml, b.yaml (c.yaml will be ignored)
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default