apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glob-numeric-prefix
spec:
  source:
    repoURL: https://github.com/nitishfy/argocd-helm-example.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
      - values/numeric-prefix/*.yaml # 00-, 10-, 20- will be applied in that order
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default