apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glob-double-star
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-valueFiles-glob
    helm:
      valueFiles:
      - values/double-star/**/*.yaml # a.yaml, b.yaml, nested/c.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default