apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-100
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:dgadavin/argocd-example-apps.git
    targetRevision: test-100
    path: helm-dependency
  destination:
    server: https://kubernetes.default.svc
    namespace: test-100
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
