apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
#    successCondition: isNaN(result[0]) || result[0] >= 0.10
    successCondition: result[0] >= 0.01
    provider:
      prometheus:
        address: "http://52.149.216.245:9090"
        query: |
          rate(nginx_ingress_controller_requests{ingress="aks-guestbook-helm-guestbook", controller_class="nginx",exported_namespace="aks-guestbook-helm-guestbook",status=~"[2].*"}[1h])