apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anbu-gabs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helm-guestbook.fullname" . }}
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
