apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: team-frontend
spec:
  generators:
    - list:
        elements:
          - service: api
          - service: worker
  template:
    metadata:
      name: '{{service}}'
      # Generated Applications will be in team-frontend namespace (same as ApplicationSet)
    spec:
      project: team-frontend
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: lightweight/app-b
      destination:
        server: https://kubernetes.default.svc
        namespace: 'team-frontend-{{service}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
