apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbooks
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: guestbook
        path: guestbook
        namespace: appset-guestbook
      - name: helm-guestbook
        path: helm-guestbook
        namespace: appset-helm-guestbook
      - name: kustomize-guestbook
        path: kustomize-guestbook
        namespace: appset-kustomize-guestbook
  template:
    metadata:
      name: 'appset-{{name}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
