apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: 'appset-list-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: lightweight/app-a
      destination:
        server: https://kubernetes.default.svc
        namespace: 'appset-list-{{env}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
