apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: merge
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - env
        generators:
          - list:
              elements:
                - env: dev
                  region: us-east
                - env: prod
                  region: us-west
          - list:
              elements:
                - env: dev
                  tier: low
                - env: prod
                  tier: high
  template:
    metadata:
      name: 'appset-merge-{{env}}'
      annotations:
        appset.demo/region: '{{region}}'
        appset.demo/tier: '{{tier}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: lightweight/app-a
      destination:
        server: https://kubernetes.default.svc
        namespace: 'appset-merge-{{env}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
